sudo: required
language: cpp
branches:
    only:
        - 'master'

compiler:
    - clang
    - gcc

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
      - clang
script:
    - make
