sudo: required
language: cpp
branches:
    only:
        - 'master'

compiler:
    - clang
    - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
script:
    - make
