sudo: required
language: cpp
branches:
    only:
        - 'master'

compiler:
    - clang
    - gcc

before_install:
    - if ["$CXX" == "g++"]; then sudo apt-get install -qq g++-4.8; fi
script:
    - make
